export namespace LangClassifers {

    export type LangStr = 'en' | 'es';

    export interface ILangClassifier {
        classify: (text: string) => LangStr;
    }

    /**
     * The raw algorithm should work like this:
     *
     * - Create profiles for each language below
     * - Create one for the input text.
     * - Score each lang profile against the input text profile
     * - Return the top profile.
     */
    export function create(): ILangClassifier {

        function classify(text: string): LangStr {
            return 'en';
        }

        return {classify};

    }

}

export const ES = "La Segunda Guerra Mundial fue un conflicto militar global que se desarrolló entre 1939 y 1945. En ella se vieron implicadas la mayor parte de las naciones del mundo, incluidas todas las grandes potencias, así como prácticamente todas las naciones europeas, agrupadas en dos alianzas militares enfrentadas: los aliados de la Segunda Guerra Mundial y las potencias del eje. Fue la mayor contienda bélica de la historia, con más de cien millones de militares movilizados y un estado de «guerra total» en que los grandes contendientes destinaron toda su capacidad económica, militar y científica al servicio del esfuerzo bélico, borrando la distinción entre recursos civiles y militares. Marcada por hechos de enorme repercusión que incluyeron la muerte masiva de civiles —el Holocausto, los bombardeos intensivos sobre ciudades y el uso, por única vez, de armas nucleares en un conflicto militar— la Segunda Guerra Mundial fue la más mortífera de la historia con un resultado de entre 50 y 70 millones de víctimas, el 2,5 % de la población mundial.1​\n" +
    "\n" +
    "El comienzo del conflicto se suele situar en el 1 de septiembre de 1939, con la invasión alemana de Polonia, el primer paso bélico de la Alemania nazi en su pretensión de fundar un Tercer Reich alemán sobre Europa, y la consiguiente declaración de guerra a Alemania el 3 de septiembre por parte de Reino Unido, Francia y países afines de la Mancomunidad de Naciones. Desde finales de 1939 hasta inicios de 1941, merced a una serie de fulgurantes campañas militares y la firma de tratados, Alemania conquistó o sometió gran parte de la Europa continental. En virtud de los acuerdos firmados entre los nazis y los soviéticos, la nominalmente neutral Unión Soviética ocupó o se anexionó territorios de las seis naciones vecinas con las que compartía frontera en el oeste. El Reino Unido y la Commonwealth se mantuvieron como la única gran fuerza capaz de combatir contra las potencias del eje en el Norte de África y en una extensa guerra naval. En junio de 1941 las potencias europeas del eje comenzaron la invasión de la Unión Soviética, iniciando así la más extensa operación de guerra terrestre de la Historia, en la que desde ese momento se empleó la mayor parte del poder militar del Eje. En diciembre de 1941 el Imperio del Japón, que había estado en guerra con China desde 19372​3​ y pretendía expandir sus dominios en el Sudeste Asiático, atacó a los Estados Unidos y a las posesiones europeas, francesas, británicas y neerlandeses en Asia y el océano Pacífico, conquistando rápidamente gran parte de la región.\n" +
    "\n" +
    "El avance de las fuerzas del Eje fue detenido por los aliados en 1942 tras la derrota de Japón en varias batallas navales y de las tropas europeas del Eje en el Norte de África y en la decisiva batalla de Stalingrado. En 1943, como consecuencia de los diversos reveses de los alemanes en Europa del Este, la invasión aliada de la Italia Fascista y las victorias de los Estados Unidos en el Pacífico, el Eje perdió la iniciativa y tuvo que emprender la retirada estratégica en todos los frentes. En 1944 los aliados occidentales invadieron Francia, al mismo tiempo que la Unión Soviética recuperaba las pérdidas territoriales y ambas potencias invadían Alemania.\n" +
    "\n" +
    "La guerra acabó con una victoria total de los aliados sobre el eje en 1945 y la liberación de los prisioneros en campos de exterminio. La guerra en Europa terminó con la captura de Berlín por tropas soviéticas y polacas y la consiguiente rendición incondicional alemana el 8 de mayo de 1945. La Armada Imperial Japonesa resultó derrotada por los Estados Unidos y la invasión del archipiélago japonés se hizo inminente. Tras el bombardeo atómico sobre Hiroshima y Nagasaki por parte de los Estados Unidos y la invasión soviética de Manchuria, la guerra en Asia terminó el 15 de agosto de 1945 cuando Japón aceptó la rendición incondicional.\n" +
    "\n" +
    "La Segunda Guerra Mundial alteró las relaciones políticas y la estructura social del mundo. La Organización de las Naciones Unidas (ONU) fue creada tras la conflagración para fomentar la cooperación internacional y prevenir futuros conflictos. La Unión Soviética y los Estados Unidos se alzaron como superpotencias rivales, estableciéndose el escenario para la Guerra Fría, que se prolongó por los siguientes 46 años. Al mismo tiempo declinó la influencia de las grandes potencias europeas, materializada en el inicio de la descolonización de Asia y África. La mayoría de los países cuyas industrias habían sido dañadas iniciaron la recuperación económica, mientras que la integración política, especialmente en Europa, emergió como un esfuerzo para establecer las relaciones de posguerra.";

export const EN = "World War II or the Second World War, often abbreviated as WWII or WW2, was a global war that lasted from 1939 to 1945. It involved the vast majority of the world's countries—including all of the great powers—forming two opposing military alliances: the Allies and the Axis powers. In a total war directly involving more than 100 million personnel from more than 30 countries, the major participants threw their entire economic, industrial, and scientific capabilities behind the war effort, blurring the distinction between civilian and military resources. Aircraft played a major role in the conflict, enabling the strategic bombing of population centres and the only two uses of nuclear weapons in war to this day. World War II was by far the deadliest conflict in human history, and resulted in 70 to 85 million fatalities, a majority being civilians. Tens of millions of people died due to genocides (including the Holocaust), starvation, massacres, and disease. In the wake of the Axis defeat, Germany and Japan were occupied, and war crimes tribunals were conducted against German and Japanese leaders.\n" +
    "\n" +
    "World War II is generally considered to have begun on 1 September 1939, when Nazi Germany, under Adolf Hitler, invaded Poland. The United Kingdom and France subsequently declared war on Germany on the 3rd. Under the Molotov–Ribbentrop Pact of August 1939, Germany and the Soviet Union had partitioned Poland and marked out their \"spheres of influence\" across Finland, Romania and the Baltic states. From late 1939 to early 1941, in a series of campaigns and treaties, Germany conquered or controlled much of continental Europe, and formed the Axis alliance with Italy and Japan (along with other countries later on). Following the onset of campaigns in North Africa and East Africa, and the fall of France in mid-1940, the war continued primarily between the European Axis powers and the British Empire, with war in the Balkans, the aerial Battle of Britain, the Blitz of the UK, and the Battle of the Atlantic. On 22 June 1941, Germany led the European Axis powers in an invasion of the Soviet Union, opening the Eastern Front, the largest land theatre of war in history and trapping the Axis powers, crucially the German Wehrmacht, in a war of attrition.\n" +
    "\n" +
    "Japan, which aimed to dominate Asia and the Pacific, was at war with the Republic of China by 1937. In December 1941, Japan attacked American and British territories with near-simultaneous offensives against Southeast Asia and the Central Pacific, including an attack on the US fleet at Pearl Harbor which forced the US to declare war against Japan; the European Axis powers declared war on the US in solidarity. Japan soon captured much of the western Pacific, but its advances were halted in 1942 after losing the critical Battle of Midway; later, Germany and Italy were defeated in North Africa and at Stalingrad in the Soviet Union. Key setbacks in 1943—including a series of German defeats on the Eastern Front, the Allied invasions of Sicily and the Italian mainland, and Allied offensives in the Pacific—cost the Axis powers their initiative and forced it into strategic retreat on all fronts. In 1944, the Western Allies invaded German-occupied France, while the Soviet Union regained its territorial losses and turned towards Germany and its allies. During 1944 and 1945, Japan suffered reversals in mainland Asia, while the Allies crippled the Japanese Navy and captured key western Pacific islands.\n" +
    "\n" +
    "The war in Europe concluded with the liberation of German-occupied territories, and the invasion of Germany by the Western Allies and the Soviet Union, culminating in the fall of Berlin to Soviet troops, Hitler's suicide and the German unconditional surrender on 8 May 1945. Following the Potsdam Declaration by the Allies on 26 July 1945 and the refusal of Japan to surrender on its terms, the United States dropped the first atomic bombs on the Japanese cities of Hiroshima, on 6 August, and Nagasaki, on 9 August. Faced with an imminent invasion of the Japanese archipelago, the possibility of additional atomic bombings, and the Soviet entry into the war against Japan and its invasion of Manchuria, Japan announced its intention to surrender on 15 August, then signed the surrender document on 2 September 1945, cementing total victory in Asia for the Allies.";
